# ./Dockerfile

FROM elixir:latest

RUN mkdir /app
COPY . /app
WORKDIR /app

RUN mix local.hex --force
RUN mix local.rebar --force

COPY mix.exs mix.lock ./
COPY config config

RUN mix do deps.get, deps.compile

COPY priv priv
COPY lib lib

COPY docker_dev_start.sh docker_dev_start.sh
# Compile the project.
# RUN mix do compile
# CMD ["mix", "phx.server"]

EXPOSE 4000
